name: documentation

on:
    workflow_call:
        secrets:
            GITHUB_TOKEN1:
              required: true
              description: 'The GitHub token for the repository.'

permissions:
    contents: write

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v3
        - name: Install dependencies
          run: |
            pip install sphinx sphinx_rtd_theme myst_parser sphinx-copybutton sphinx-multiversion
        - name: install requirements with no dependencies
          run: |
            pip install -r requirements.txt --no-dependencies
        - name: Sphinx build
          run: |
            sphinx-build docs/source _build
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            publish_branch: gh-pages
            github_token: ${{ secrets.GITHUB_TOKEN1 }}
            publish_dir: _build/
            force_orphan: true