

parameters:
  - name: feed_name
    default: packages
  - name: python_version
    default: '3.7'

stages:
  - stage: package_test
    displayName: Execute unit testing and integration test for package deployment
    jobs:
      - job:
        steps:
          - script: echo generate test

  - stage: package_build_and_upload
    displayName: Load package to Azure DevOps feed
    condition: succeeded()
    jobs:
      - job:
        steps:
          - task: UsePythonVersion@0
            inputs:
              addToPath: true
              versionSpec: ${{ parameters.python_version }}

          - script: pip install wheel twine
            displayName: Install dependencies

          - task: TwineAuthenticate@1
            displayName: Autenticate to feed $(feed_name)
            inputs:
              artifactFeed: $(feed_name)

          - script: python setup.py bdist_wheel
            displayName: Generate package

          - script: python -m twine upload -r $(feed_name) --config-file $(PYPIRC_PATH) dist/*
            displayName: Upload package

  - stage: package_documentation
    displayName: Generate package documentation
    condition: succeeded()
    jobs:
      - job:
        steps:
          - script: echo generate package documentation
